services:
  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=db_docker_utn
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=db_docker_utn
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_docker_utn"]
      interval: 5s
      timeout: 3s
      retries: 5
secrets:
  db-password:
    file: db/password.txt