<!DOCTYPE HTML>
<html>
<head>
  <title>Getting Started: Serving Web Content</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body>

  <h1> Fecha y hora con la que se ha ejecutado el endpoint para agregar una fecha </h1>

	<h2>${dates}</h2>
  
  <a href="/new-date"><h1> Agregar una fecha</h1> </a>
  <a href="/delete-all"> <h1> Eliminar todos los registros </h1>  </a>

</body>
